.TH QUEST 1 quest\-VERSION
.SH NAME
quest \- speedrun timer
.SH SYNOPSIS
.B quest
.IR file
.SH DESCRIPTION
quest provides a timer for timing speedruns of video games, with features
speedrunners expect of such software like splitting the timer between named
segments and displaying comparisons between a known previous time such as
a personal best or world record.
.PP
I/O features such as importing split names from a splits.io run file/exporting
runs to the splits.io generic exchange format and global hotkeys to control the
software while a video game has window focus are also supported.
.SH OPTIONS

